GENERIC_MESSAGES = {
    0: "Ha ocurrido un error desconocido",
    1: "Ha ocurrido un error interno en el servidor.",
    2: "No tiene permisos para realizar esta acción.",
    3: "El recurso solicitado no existe.",
    4: "Ya existe un registro con esos datos.",
    5: "No puede eliminar su propia cuenta.",
    6: "La contraseña debe tener al menos 6 caracteres.",
    7: "Datos de entrada inválidos.",
    8: "Credenciales inválidas.",
}

ERROR_CODES = {
    "0x00a": {
        "generic": 0,
        "description": "Este error no se ha contemplado antes y no se conoce la fuente",
    },
    "1x01a": {
        "generic": 2,
        "description": "Usuario intentó quitarse el rol de administrador",
    },
    "1x02a": {
        "generic": 2,
        "description": "Usuario intentó modificar datos de otro sin permisos",
    },
    "2x01a": {"generic": 4, "description": "Nombre de usuario ya existe al crear"},
    "2x02a": {"generic": 4, "description": "Nombre de usuario ya existe al actualizar"},
    "3x01a": {"generic": 3, "description": "Usuario no encontrado"},
    "4x01a": {"generic": 5, "description": "Intento de eliminación del propio usuario"},
    "5x01a": {"generic": 1, "description": "Error inesperado al crear usuario"},
    "5x02a": {"generic": 1, "description": "Error inesperado al actualizar usuario"},
    "5x03a": {"generic": 1, "description": "Error inesperado al deshabilitar usuario"},
    "5x04a": {"generic": 1, "description": "Error inesperado al eliminar usuario"},
    "5x05a": {"generic": 1, "description": "Error inesperado al cambiar contraseña"},
    "6x01a": {"generic": 6, "description": "Contraseña nueva demasiado corta"},
    "VAL001": {"generic": 7, "description": "Error de validación de entrada"},
    "TEST001": {"generic": 1, "description": "Error de prueba"},
    "AUTH001": {"generic": 8, "description": "Credenciales inválidas"},
    "AUTH002": {"generic": 2, "description": "Usuario inactivo"},
    "AUTH003": {"generic": 3, "description": "Sesión no encontrada"},
    "AUTH004": {"generic": 2, "description": "No se pudo identificar la sesión actual"},
    "AUTH005": {"generic": 2, "description": "Refresh token faltante"},
    "AUTH006": {"generic": 3, "description": "Sesión no encontrada"},
    "AUTH007": {"generic": 2, "description": "Sesión expirada"},
    "AUTH008": {"generic": 2, "description": "Token inválido"},
    "AUTH009": {"generic": 3, "description": "Usuario inválido"},
    "AUTH010": {"generic": 2, "description": "Token inválido"},
    "AUTH011": {"generic": 2, "description": "Token expirado"},
    "AUTH012": {"generic": 2, "description": "Token inválido"},
    "PERM001": {
        "generic": 2,
        "description": "Usuario sin el permiso requerido para esta acción",
    },
    "PERM002": {"generic": 7, "description": "ID de permiso inválido"},
    "PERM003": {"generic": 4, "description": "Ya existe un rol con ese nombre"},
}
